name: build application

on:
#   push:
#     branches:
#       - main
  workflow_dispatch: # on button click
  workflow_run:
    workflows: ["check for newer api version"]
    types:
      - completed

jobs:
  build_app:

    strategy:
      matrix:
        firmware_branch: [dev, release-candidate, release]

    name: build application
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: checkout this repo
      uses: actions/checkout@v3

    - name: checkout flipper zero firmware repo
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-firmware
        path: './flipperzero-firmware'
        submodules: true
        ref: ${{ matrix.firmware_branch }}

    - name: move app source code files
      run: mv source/* flipperzero-firmware/applications_user

    - name: build applications
      run: cd flipperzero-firmware && ./fbt faps
    
#     - name: move built applications
#       run: mv 'flipperzero-firmware/build/f7-firmware-D/.extapps/*.fap' './new_apps'
