name: build application

on:
#   push:
#     branches:
#       - main
  workflow_dispatch: # on button click
#   workflow_run:
#     workflows: ["check for newer api version"]
#     types:
#       - completed
  workflow_call: # callable from another workflow

jobs:
  build_apps:

    strategy:
      matrix:
        firmware_branch: [dev, release-candidate, release]

    name: build application
    runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: ${{ github.jobs.check_api_version.result == 'success' }}
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: checkout flipper zero firmware repo
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: './flipperzero-firmware'
          submodules: true
          ref: ${{ matrix.firmware_branch }}

      - name: move source code
        run: mv source/* flipperzero-firmware/applications_user

      - name: build
        run: cd flipperzero-firmware && ./fbt faps

      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add flipperzero-firmware/build/f7-firmware-D/.extapps/*.fap
          git commit -m "built flipper apps via build_apps workflow"
          git push
