name: build FAPs

on:
  push:
    branches:
      - main
  workflow_dispatch: # on button click
  workflow_call:

jobs:
  build_apps:

    strategy:
      matrix:
        firmware_branch: [dev, release-candidate, release]

    name: build application
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: api_versions
          path: t

      - name: checkout this repo
        uses: actions/checkout@v3

      - name: checkout flipper zero firmware repo
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: './flipperzero-firmware'
          submodules: true
          ref: ${{ matrix.firmware_branch }}

      - name: build
        run: |
          mv source/* flipperzero-firmware/applications_user
          cd flipperzero-firmware && ./fbt faps

      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add flipperzero-firmware/build/f7-firmware-D/.extapps/*.fap
          git commit -m "built flipper apps via build_apps workflow"
          git push

