name: check for newer api version

on:
  schedule:
    - cron: '49 * * * *'
  workflow_dispatch: # on button click

jobs:
  check_api_version:
    name: check for newer api version
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: get current version
        id: get_current
        run: |
          echo "CURRENT=$(sed -n '1p' api_versions.csv | awk -F ',' '{print $3}')" >> "$GITHUB_ENV"

      - name: checkout upstream repo
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: './flipperzero-firmware'
      
      - name: get upstream API version
        id: get_upstream
        run: |
          echo "UPSTREAM=$(sed -n '2p' flipperzero-firmware/firmware/targets/f7/api_symbols.csv | awk -F ',' '{print $3}')" >> $GITHUB_ENV
          echo "FULL_UPSTREAM=$(sed -n '2p' flipperzero-firmware/firmware/targets/f7/api_symbols.csv)" >> $GITHUB_ENV

      - name: compare versions and push
        if: ${{ env.CURRENT < env.UPSTREAM }}
        run: |
          echo "newer API version detected upstream"
          sed -i "1s@^@${FULL_UPSTREAM}\\n@" api_versions.csv
          git --no-pager diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add api_versions.csv
          git commit -m "update api_versions"
          git push

  build_apps:
    if: ${{ jobs.check_api_version.result != 'skipped' }}
    uses: ./.github/workflows/build_apps.yml

    

#       - name: no update
#         if: ${{ env.CURRENT >= env.UPSTREAM }}
#         run: echo "no update required" && exit 1
