name: compare api versions

on:
  schedule:
    - cron: '49 * * * *'
  workflow_dispatch: # on button click

jobs:
  compare_api_versions:
    name: compare api versions
    strategy:
      matrix:
        firmware_branch: [dev, release-candidate, release]
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: get current version
        id: get_current
        run: |
          echo "CURRENT=$(yq -r '.versions.${{ matrix.firmware_branch }}' api_versions.yaml)" >> "$GITHUB_ENV"
          

      - name: checkout upstream repo
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: './flipperzero-firmware'
          ref: ${{ matrix.firmware_branch }}
          submodules: true
      
      - name: get upstream API version
        id: get_upstream
        run: |
          echo "UPSTREAM=$(awk -F ',' 'NR==2{print $3}' flipperzero-firmware/firmware/targets/f7/api_symbols.csv)" >> $GITHUB_ENV

      - name: update api_versions.yaml
        id: update_version
        if: ${{ env.CURRENT < env.UPSTREAM }}
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'api_versions.yaml'
          propertyPath: versions['${{ matrix.firmware_branch }}']
          value: ${{ env.UPSTREAM }}
          commitChange: false
          method: Update

      - name: push api_versions.yaml changes
        if: ${{ steps.update_version.conclusion != 'skipped' }}
        run: |
          git --no-pager diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add api_versions.yaml
          git commit -m "update api_versions"
          git push

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        if: ${{ steps.update_version.conclusion != 'skipped' }}
        with:
          name: api_versions
          path: api_versions.yml
          retention-days: 1

  build:
    uses: ./.github/workflows/build_apps.yml
    needs: compare_api_versions
