name: "FAP: Compare API Versions"

on:
  schedule:
    - cron: '49 * * * *'
  workflow_dispatch: # on button click

jobs:
  compare_api_versions:
    name: compare api versions
    strategy:
      matrix:
#         firmware_branch: [dev, rc, release]
        include:
          - name: dev
            sdk-channel: dev
          - name: release
            sdk-channel: release
          - name: release-candidate
            sdk-channel: rc
#           - name: Unofficial firmware
#             # example URL, replace with a valid one
#             # you can also use other modes for specifying SDK sources
#             sdk-index-url: https://flipper.example.com/directory.json
#             sdk-channel: dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: get current version
        id: get_current
        run: |
          echo "CURRENT=$(yq -r '.versions.${{ matrix.sdk-channel }}' api_versions.yaml)" >> "$GITHUB_ENV"
          
      - name: checkout upstream repo
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: './flipperzero-firmware'
          ref: ${{ matrix.name }}
          submodules: true
      
      - name: get upstream API version
        id: get_upstream
        run: |
          echo "UPSTREAM=$(awk -F ',' 'NR==2{print $3}' flipperzero-firmware/firmware/targets/f7/api_symbols.csv)" >> $GITHUB_ENV

      - name: update api_versions.yaml
        id: update_version
        if: ${{ env.CURRENT < env.UPSTREAM }}
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'api_versions.yaml'
          propertyPath: versions['${{ matrix.sdk-channel }}']
          value: ${{ env.UPSTREAM }}
          commitChange: true
          method: Update

      - name: push api_versions.yaml changes
        if: ${{ steps.update_version.conclusion != 'skipped' }}
        run: |
          git pull
          git --no-pager diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add api_versions.yaml
          git commit -m "update api_versions"
          git push

      - name: build with ufbt
        if: ${{ steps.update_version.conclusion != 'skipped' }}
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: "./source/dolphin-counter-main"

      - name: upload app artifacts
        if: ${{ steps.build-app.conclusion != 'skipped' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

#       - name: create yaml file artifact
#         uses: actions/upload-artifact@v3.1.2
#         if: ${{ steps.update_version.conclusion != 'skipped' }}
#         with:
#           name: api_versions
#           path: api_versions.yaml
#           retention-days: 1

#   build:
#     uses: ./.github/workflows/build_apps.yml
#     needs: compare_api_versions
