name: "FAP: Build for multiple SDK sources"
on:
  push:
    branches:
      - main
  workflow_dispatch: # on click
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [dev, rc, release]
    name: 'ufbt: build for ${{ matrix.channel }}'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: pwd && ls
      - name: build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.channel }}
          app-dir: "./source"
      - name: upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
