on:
  push:
    branches:
    - main
    
jobs:
  build_app:
    name: build application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-firmware
        path: './flipperzero-firmware'

    - name: move files
      run: mv source/* flipperzero-firmware/applications_user && ls flipperzero-firmware/applications_user


#     - name: build
#     - run: './fbt faps'
