on:
  push:
    branches:
    - main

jobs:
  build_app:

    strategy:
      matrix:
        firmware_branch: [dev, release-candidate, release]

    name: build application
    runs-on: ubuntu-latest
    steps:
    - name: checkout this repo
      uses: actions/checkout@v3

    - name: checkout flipper zero firmware repo
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-firmware
        path: './flipperzero-firmware'
        submodules: true
        ref: ${{ matrix.firmware_branch }}

    - name: move app source code files
      run: mv source/* flipperzero-firmware/applications_user

    - name: build applications
      run: cd flipperzero-firmware && ./fbt fap_counter
    
#     - name: move built applications
#       run: mv 'flipperzero-firmware/build/f7-firmware-D/.extapps/*.fap' './new_apps'
