on:
  push:
    branches:
    - main

jobs:
  build_app:

    name: build application
    runs-on: ubuntu-latest
    steps:
    
    - name: install packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib python3 curl zip unzip
          sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev

    - name: checkout this repo
      uses: actions/checkout@v3

    - name: checkout flipper zero firmware repo
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-firmware
        path: './flipperzero-firmware'
        submodules: true

    - name: move app source code files
      run: mv source/* flipperzero-firmware/applications_user

    - name: build applications
      run: './flipperzero-firmware/fbt faps'
    
#     - name: move built applications
#       run: mv 'flipperzero-firmware/build/f7-firmware-D/.extapps/*.fap' './new_apps'
